### PR TITLE
Replaced use of deprecated 'filtered', 'and', 'not' and 'query' filter (needed for SD-4323)

### PR DESCRIPTION
**Pull request by jerome-poisson**
this need extensive review and testing.

in several places 'not' has been replaced by 'bool': {'must_not': …} which should be fine, but a refactoring may be needed in the future to place the 'must_not' in a upper level

the patchs on *spec.js file need most probably to be adjusted

### CODE REVIEW

**Comment by akintolga** [comment]
I can't see how this change related with SD-4324...

**Comment by Michael-Gourlay** [comment]
@akintolga shld be SD-4323

**Comment by jerome-poisson** [comment]
Oh yes sorry, SD-4323

**Comment by gbbr** [comment]
@jerome-poisson this is 3 months old - shall we close it ?

**Comment by jerome-poisson** [comment]
@gbbr no, the task is not done and we'll talk about it at SourceCamp, this P.R. may be outdated but still we can use it as a basis.

**Comment by ioanpocol** [comment]
@petrjasek @jerome-poisson  Can we fix this PR and update elastic search to a newer version?

**Comment by gbbr** [comment]
I'm closing this for now. We can re-open later when @jerome-poisson is back.

**Pull request closed without merging**
