### PR TITLE
[SDESK-1382]: template editor modal

### PR DESCRIPTION
**Pull request by darconny**
- UI improvements

### CODE REVIEW

**Comment by petrjasek** [comment]
seems like this requires some e2e test changes to pass

**Comment by pavlovicnemanja** [comment]
hey @petrjasek, @ioanpocol and me were testing this locally, and everything seems to be fine. Not sure why this is constantly failing on same place. Some idea how to proceed whit this?

**Comment by petrjasek** [comment]
this should fix it:
```
scripts/apps/templates/views/template-editor-modal.html
-                <div sd-toggle-box data-title="{{:: 'Metadata' | translate }}" data-open="false">
+                <div id="template-editor-metadata"
+                    sd-toggle-box data-title="{{:: 'Metadata' | translate }}" data-open="false">
spec/helpers/templates.js b/spec/helpers/templates.js
-    this.toggleMetadata = () => element(by.className('toggle-box__header')).click();
+    this.toggleMetadata = () => element(by.id('template-editor-metadata')).click();
```
problem is there is a new `sd-toggle-box` used and in e2e tests it was assuming the first one is metadata toggle, now it's desks

**Comment by darconny** [comment]
Thanks @petrjasek, it worked finally.

**Pull request merged**
