### PR TITLE
Authoring refactoring post big merge

### PR DESCRIPTION
**Pull request by tomaskikutis**
SDESK-7141

@petrjasek I've removed all intermediary branches. I suggest to merge this soon and then address unit and e2e tests later which I didn't have the time to look at.

### CODE REVIEW

**Comment by petrjasek** [comment]
I would fix the build first, trying to run the branch linked locally but seems like there are some issues atm

**Comment by petrjasek** [comment]
can you pls merge develop here as well @tomaskikutis ? it doesn't have the updated e2e data setup atm

**Comment by tomaskikutis** [comment]
It is merged, I see the [record restoring](https://github.com/superdesk/superdesk-client-core/blob/authoring-refactoring-post-big-merge/e2e/client/specs/helpers/fixtures.ts#L6) being used and the [dumps are there](https://github.com/superdesk/superdesk-client-core/tree/authoring-refactoring-post-big-merge/e2e/server/dump) too.

It might be that I did a mistake when resolving conflicts and some piece got lost, but I don't think so. I've checked out [your original commit](https://github.com/superdesk/superdesk-client-core/commit/8c466291f7dda8a76b9007170d818824689b36c1) - undid it, stashed it, navigated to `authoring-refactoring-post-big-merge` and applied the stash. It caused no changes to appear.

If you find something missing maybe you could manually put it back yourself?

**Comment by petrjasek** [comment]
my bad, forgot to pull locally

**Comment by tomaskikutis** [comment]
Yep, let's not squash it.

**Comment by tomaskikutis** [comment]
can you approve the PR so I can merge it?

**Review by petrjasek — APPROVED** [review]

**Pull request merged**
