### PR TITLE
Updating search results after multi send fixed.

### PR DESCRIPTION
**Pull request by eozan**
SD-4807

### CODE REVIEW

**Comment by petrjasek** [comment]
imo would be better to fetch single item instead of reloading the whole thing, also this change might not be available yet due to elastic caching, but will be there if you get item by id. but probably you get the updated item from server already, so it's just a matter of updating that item in list

**Comment by eozan** [comment]
This is done the same way authoring>sendTo works. Imo, let's add a refactoring task to fix all of them together, if this is the wrong way.

**Comment by eozan** [comment]
Now changed to update only sent item.

**Comment by mugurrus** [comment]
:+1:

**Pull request merged**
