### PR TITLE
ui(fix): fix a problem where a directive wasn't loaded via ng-class

### PR DESCRIPTION
**Pull request by gbbr**
Revert a regression from #644 and fixes SD-4648

### CODE REVIEW

**Comment by vied12** [comment]
:+1:

**Comment by gbbr** [comment]
I've made further changes, PTAL

**Comment by pavlovicnemanja** [comment]
:+1:

**Comment by Aca-jov** [comment]
:+1:

**Comment by vied12** [comment]
:+1:

**Pull request merged**
