### PR TITLE
fixed mark for highlight data

### PR DESCRIPTION
**Pull request by dzonidoo**
SDESK-6948

### CODE REVIEW

**Comment by tomaskikutis** [comment]
what's wrong with CI?

**Comment by tomaskikutis** [comment]
I will take a look at e2e issue

**Comment by tomaskikutis** [comment]
```
INFO: pip is looking at multiple versions of superdesk-core to determine which version is compatible with other requirements. This could take a while.
  ERROR: Could not find a version that satisfies the requirement celery[redis]<5.3,>=5.2.7 (from superdesk-core)
```

@petrjasek can you update e2e to work against develop for e2e to pass? It's failing because old server is still expecting highlights to be a string. I tried updating it myself using `pip-compile` but it didn't work

**Comment by tomaskikutis** [comment]
@dzonidoo update your branch from develop and see if e2e is good now

**Comment by tomaskikutis** [comment]
@petrjasek I was running e2e against `hotfix/2.6.5` branch as you specified, but the server still complains about the array and expects a string. Are you sure it's a correct version to use?

```
# GET /api/marked_for_highlights
{
    "_status": "ERR",
    "_issues": {
        "highlights": "must be of string type"
    },
    "_error": {
        "code": 400,
        "message": "Insertion failure: 1 document(s) contain(s) error(s)"
    }
}
```

**Comment by petrjasek** [comment]
@tomaskikutis that wouldn't be atm in 2.6, so either develop or release/2.7

**Review by tomaskikutis — APPROVED** [review]

**Pull request merged**
