### PR TITLE
Build tools

### PR DESCRIPTION
**Pull request by tomaskikutis**
Move extension building to a separate package. [Here's how](https://user-images.githubusercontent.com/2076953/118807545-bd9afe00-b8a8-11eb-97a9-4f10c9fb6671.png) it would be enabled in root repositories.

There's also a task to convert .po to .json files, that will allow including translations from extensions.

### CODE REVIEW

**Comment by petrjasek** [comment]
so how would it get the po files from planning and combine that with po files from core?

**Comment by tomaskikutis** [comment]
I'm still working on that part. In order to get translations from extensions, I'd need to get extension directories. That was already implemented in extension build scripts and you asked about removing `build-extensions.js` from the root repository so I first moved the build scripts and will now implement combining translations.

**Review by MarkLark86 — APPROVED** [review]

**Comment by MarkLark86** [comment]
Looks okay to me

**Comment by petrjasek** [comment]
that `file:../../` path in package.json from the example goes where?

**Comment by tomaskikutis** [comment]
It's not only an example, it's used to build translations before running e2e tests.
`file: build-tools` is the same as `file: ./build-tools` - it looks for a directory and `package.json` in that directory.

**Comment by petrjasek** [comment]
yep I'm just wondering how to reference the build tools in eg superdesk-cp repo

**Comment by tomaskikutis** [comment]
Ah, you mean that example. I will release a npm package after this PR is merged.

**Review by petrjasek — APPROVED** [review]

**Pull request merged**
