### PR TITLE
sync item associations on client

### PR DESCRIPTION
**Pull request by petrjasek**
atm it's done on server on save, but if user publishes without
saving first associations data is missing or incomplete

SDESK-4015

### CODE REVIEW

**Comment by tomaskikutis** [comment]
How is it possible to publish without saving first?

**Comment by karelpetrak** [comment]
@tomaskikutis I think what Petr means is when you do not explicitly save (hit the save button) but proceed to publish (and the item is saved as a part of the "publish" workflow).

**Comment by tomaskikutis** [comment]
How about running the same code no matter if saving happens via save button or as a part of publishing workflow?

**Comment by petrjasek** [comment]
@tomaskikutis yep that makes sense, but not sure how it's related to this fix. imo it's better to send correct data all the time

**Comment by tomaskikutis** [comment]
I do agree, that it's better to send correct data all the time, but the function which returns bad results should be fixed instead of having an extra function which fixes the bad output of the first one. Or isn't that the case?

**Comment by petrjasek** [comment]
that part is done on server, it was syncing the data only on save, now that part is gone

**Comment by tomaskikutis** [comment]
Which line on the server is doing this? Are you saying that if I take this PR and remove the sync function, all associations including images, gallery, related media won't appear in items' `associations` field?

**Comment by petrjasek** [comment]
https://github.com/superdesk/superdesk-core/blob/master/apps/archive/archive.py#L94-L114

it will only appear there on save

**Comment by tomaskikutis** [comment]
If the code which saves the item is also updating the associations, why can't we run the same code(which does the saving) before publishing? It would update the associations and we'd avoid duplicating code between client/server.

It might require a bit more work, but it's much more sustainable since every future change in update logic would automatically get applied when saving.

**Comment by petrjasek** [comment]
the idea is to remove that code from server once this PR is merged

**Comment by tomaskikutis** [comment]
That makes more sense now. Do you know why [update_associations](https://github.com/superdesk/superdesk-core/blob/master/apps/archive/archive.py#L94-L114) function exists in the first place? Why individual components can't take care of updating the field. I don't mind if it's done the same way across the app, but I see some components like related items writing to `item.associations` directly.

@ioanpocol I see you implemented [update_associations](https://github.com/superdesk/superdesk-core/blob/master/apps/archive/archive.py#L94-L114), do you remember what was the case? I can't find the ticket reference in [the PR](https://github.com/superdesk/superdesk-core/pull/1081).

**Comment by ioanpocol** [comment]
All images added to editor3 should also appear on associations.  So update_associations function process editor3 state and update the associations.  I don't know why this has been implemented on . backend and not on frontend.

**Comment by tomaskikutis** [comment]
Thanks, Ioan. I now see that we don't update associations when images or embeds change in editor3 and leave it up to the synchronizer function.

**Pull request merged**
