### PR TITLE
SDESK-1983 | Hide keywords in metadata if they are not enabled in content profile

### PR DESCRIPTION
**Pull request by pablopunk**

### CODE REVIEW

**Comment by petrjasek** [comment]
maybe we should remove that field from the sidebar, when it's in schema it's also in the autoring isn't it?

**Comment by pablopunk** [comment]
@petrjasek what is the authoring 🤔

**Comment by petrjasek** [comment]
keywords
it's there on the left - the field with focus - and in the sidebar

**Comment by pablopunk** [comment]
@petrjasek oh gotcha. Yes you're right, that's what I was talking about in the meeting, but maybe someone uses the sidebar all the time even if we have it in the authoring already.

**Pull request merged**
