### PR TITLE
fix(archive): remove exif-js from index imports

### PR DESCRIPTION
**Pull request by thnkloud9**
This change fixes an issue that prevents media uploads.  wanted to add e2e test for upload, but looks to be not possible for now.

### CODE REVIEW

**Comment by gbbr** [comment]
Thanks @thnkloud9 LGTM 👍

**Comment by petrjasek** [comment]
:+1:

**Comment by akintolga** [comment]
:+1:

**Comment by gbbr** [comment]
I think the build should be fine if you rebase on master - not sure why it keeps failing. I've tried restarting it.

**Pull request merged**
