### PR TITLE
Preserve data while drag-and-droping an image to the body

### PR DESCRIPTION
**Pull request by tomaskikutis**
SDESK-1508

### CODE REVIEW

**Comment by petrjasek** [comment]
I think it might make sense to fetch the item from server on drop to get the data, instead of fetching it all the time

**Comment by tomaskikutis** [comment]
Ok, I will try to do that. Anyway, why are we not fetching everything every time? It would prevent such bugs and it doesn't seem it would put significantly more load on the database if it's a single object in mongo anyway?

**Comment by petrjasek** [comment]
it's there to limit the response size

**Comment by tomaskikutis** [comment]
Does it matter if it's 20kb or 200kb?

**Comment by tomaskikutis** [comment]
I agree, that it's nice to have smaller payloads, and use less data, but if we can't safely do that without causing bugs, that 200kb doesn't sound so bad anymore.

**Comment by petrjasek** [comment]
thing is it's not fetched once, but all the time by all users

**Comment by tomaskikutis** [comment]
Yeah, I know, but it still takes <300ms to fetch on a fast network. I guess the problems arise when internet connections aren't that fast.

**Comment by petrjasek** [comment]
yep those fields won't be probably populated usually so atm it shouldn't be a big deal

**Pull request merged**
