### PR TITLE
SD-5346 : A maximum of 25 desks are displayed

### PR DESCRIPTION
**Pull request by naomiaro**
checking the UI for other limit issues still, should extract fetchAll to a service or something.

### CODE REVIEW

**Comment by naomiaro** [comment]
depends on https://github.com/superdesk/superdesk-core/pull/555

**Comment by akintolga** [comment]
:+1:

**Comment by ioanpocol** [comment]
@naomiaro  This PR is very old. Can you fix or close it?

**Comment by gbbr** [comment]
I'm closing this one. It's super antique. Feel free to re-open if needed.

**Comment by Michael-Gourlay** [comment]
@akintolga @ioanpocol @naomiaro @gbbr The original ticket is still alive in Jira as SDESK-256 and the problem remains unfixed. AAP have more than 25 desks configured so this continues to be an issue in the UI. Can somebody please kick a fix over the line?

**Comment by akintolga** [comment]
@Michael-Gourlay We'll taking this over to our sprint...

**Pull request closed without merging**
