### PR TITLE
Fix protractor version, because error: "Jasmine spec timed out..."

### PR DESCRIPTION
**Pull request by naspeh**
Builds are failing now on new infrastructure and Travis.

A lot of such errors:
```
FA Jasmine spec timed out. Resetting the WebDriver Control Flow.
at subscribers: list subscriber
FA Jasmine spec timed out. Resetting the WebDriver Control Flow.
at subscribers: save button is disabled when subscriber type is changed
FA Jasmine spec timed out. Resetting the WebDriver Control Flow.
at workspace: can switch views by keyboard
FA Jasmine spec timed out. Resetting the WebDriver Control Flow.
at spike: can spike item
```
It's started with `protractor@4.0.12`

### CODE REVIEW

**Comment by naspeh** [comment]
@gbbr: sure

**Comment by gbbr** [comment]
YEY

**Comment by naspeh** [comment]
hm: one failed test on `fire:build`
```
104 specs, 0 failures, 12 pending specs
Finished in 1466.371 seconds
----
Failures:
1) authoring authoring operations
  Message:
    Expected 'Twoitem5 text' to be 'TwoWordsitem5 text'.
  Stack:
    Error: Failed expectation
        at Object.it (/opt/superdesk/client-core/spec/authoring_spec.js:107:41)
        at /opt/superdesk/client-core/node_modules/jasminewd2/index.js:94:23
        at new ManagedPromise (/opt/superdesk/client-core/node_modules/selenium-webdriver/lib/promise.js:1082:7)
        at controlFlowExecute (/opt/superdesk/client-core/node_modules/jasminewd2/index.js:80:18)
        at TaskQueue.execute_ (/opt/superdesk/client-core/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/opt/superdesk/client-core/node_modules/selenium-webdriver/lib/promise.js:2896:21)
        at asyncRun (/opt/superdesk/client-core/node_modules/selenium-webdriver/lib/promise.js:2820:25)
        at /opt/superdesk/client-core/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (internal/process/next_tick.js:103:7)
Pending:

1) monitoring can display embargo label when set for published item
  Temporarily disabled with xit

72 specs, 1 failure, 1 pending spec
```
I'll restart it

**Comment by naspeh** [comment]
Green.

**Pull request merged**
