### PR TITLE
avoid error reporing on travis

### PR DESCRIPTION
**Pull request by petrjasek**
it's spamming sentry

### CODE REVIEW

**Comment by petrjasek** [comment]
it's not error, but it's using error log level to get some attention

**Comment by tomaskikutis** [comment]
What about filtering all "warn" level logs when running tests instead of targeting this one specific error?

**Comment by petrjasek** [comment]
this one in particular is not a warning, but an error. and it's not always an issue, that depends on a client, that's why we have that config.

**Comment by tomaskikutis** [comment]
> this one in particular is not a warning, but an error
> it's not error, but it's using error log level to get some attention

It might be a good idea to use another log level then to separate between not important logs like deprecation info VS important warnings related to business logic. Adding a config for an individual error is not a clean solution.

**Comment by petrjasek** [comment]
might not need this after all

**Pull request closed without merging**
