### PR TITLE
SDNTB-135 change untranslated strings in SD

### PR DESCRIPTION
**Pull request by vladnicoara**

### CODE REVIEW

**Comment by Aca-jov** [comment]
:+1:

**Comment by ioanpocol** [comment]
:+1: 
Except:
Running "jshint:all" (jshint) task

   /home/travis/build/superdesk/superdesk-client-core/scripts/superdesk-authoring/authoring.js

   1649 |            template: '<span class="char-count" ng-class="{error: limit && numChars > limit}" translate> ' + gettext(' characters') + '</span>' +

                                                                                                                                                         ^ Line is too long.

**Comment by akintolga** [comment]
:+1:

**Comment by petrjasek** [comment]
:+1:

**Pull request merged**
