### PR TITLE
Create isolate scopes

### PR DESCRIPTION
**Pull request by tomaskikutis**
SDFID-364

Create isolate scopes, so a directive can be used multiple times with the same controller. It used to use the scope of the controller and if you had multiple instances, they would all display the same date from the controller scope.

### CODE REVIEW

**Comment by petrjasek** [comment]
would be better to avoid using ng-model here, we only need to watch the value and not change it, there is some overhead with parsers/validators

**Comment by tomaskikutis** [comment]
Is there a different way to tell a directive to have the variable in its own scope?

**Comment by petrjasek** [comment]
the scope is fine, but there should be no `require: 'ngModel'` and the scope param name should be different, because `ng-model` is a directive which has some overhead and handles input events,
you can make it like:
```
scope: {datetime: '='},
link: (scope) => {
    scope.$watch('datetime', (datetime) => {
         // here goes code from ngModel.$render
    });
}
```

**Comment by tomaskikutis** [comment]
Got it, thanks for the example.

**Pull request merged**
