### PR TITLE
fix(editor3): Small bug fix and add the option to move by positive an…

### PR DESCRIPTION
**Pull request by ioanpocol**
…d negative offset from start or end of selection

### CODE REVIEW

**Comment by tomaskikutis** [comment]
Don't merge it just yet, I'll check the tests

**Comment by tomaskikutis** [comment]
Tests pass, you can merge. The only ones which don't are for a feature to limit extending to a single block, and returning alternative selection instead of `null`.

It's strange that for out-of-range cases you are returning an array of nulls, why a single `null` isn't enough?

**Comment by ioanpocol** [comment]
I didn't tried but I suppose that when you destruct a null you will get an error.

**Comment by tomaskikutis** [comment]
I've checked the destrcuting, it returns `undefined` no matter if there is something inside the array or if it's empty. You could return `return {block: null, newOffset: null};` to make it consistent.

**Comment by ioanpocol** [comment]
OK, I seen now, I forgot to update those returns.

**Comment by ioanpocol** [comment]
I updated the code

**Comment by tomaskikutis** [comment]
Saw it. All good. If we were to be pedantic, we could define a variable `noValue` and use it in those 3 places, but it's just a code style thing. I don't want to cause you work, so feel free to merge it as is.

**Comment by ioanpocol** [comment]
OK, let's be pedantic :)

**Comment by tomaskikutis** [comment]
Ok, let's merge it, I have no more to suggest :smile:

**Pull request merged**
