### PR TITLE
[SD-4044] - UI: Load the crop sizes from vocabularies dynamically

### PR DESCRIPTION
**Pull request by sjunaid**

### CODE REVIEW

**Comment by petrjasek** [comment]
hey, so what is the idea? set width/height or aspect ratio?

**Comment by sjunaid** [comment]
yes it works by setting width/height in vocab, and 4-3 and 16-9 are just the names.

**Comment by akintolga** [comment]
:+1:

**Comment by mdhaman** [comment]
:+1:

**Pull request merged**
