### PR TITLE
fix(e2e): Fix e2e tests 

### PR DESCRIPTION
**Pull request by mdhaman**
fixing the e2e test for subscibers and embargo

### CODE REVIEW

**Comment by ioanpocol** [comment]
:+1:

**Comment by mdhaman** [comment]
@ioanpocol , @petrjasek  fixed following e2e test:
[SD-4181], [SD-4182], [SD-4190], [SD-4191], [SD-4180], [SD-4185]

The test mentioned in the tickets are already working:
[SD-4183], [SD-4184]

Can we merge this PR?

**Comment by pavlovicnemanja** [comment]
:+1:

**Comment by ioanpocol** [comment]
@mdhaman  Did you enabled back all required e2e tests?

**Pull request merged**
