### PR TITLE
make updating editor3 from macro configurable

### PR DESCRIPTION
**Pull request by petrjasek**

### CODE REVIEW

**Comment by tomaskikutis** [comment]
What's the purpose of this? To ignore changes? Why would we do that?

**Comment by petrjasek** [comment]
I think it doesn't call onChange because [it calls it later](https://github.com/superdesk/superdesk-client-core/blob/develop/scripts/apps/authoring/macros/macros.ts#L198) just once, so macro can update multiple editor instances and only after trigger autosave

**Comment by tomaskikutis** [comment]
I'm not entirely getting it. What problem are you solving? Does it call autosave too often or what's the issues?

**Comment by petrjasek** [comment]
I didn't change anything here, but I'm using the event in client repo where I need the autosave to be called

**Comment by tomaskikutis** [comment]
I was asking about the fix you are doing. What happens without the code in this PR that you want to change? doesn't autosave get called?

**Comment by petrjasek** [comment]
it doesn't get called in that event handler

**Pull request merged**
