### PR TITLE
feat(editor): Added indentation for paragraphs in editor [SDNTB-27]

### PR DESCRIPTION
**Pull request by pavlovicnemanja**
SDNTB-27

### CODE REVIEW

**Comment by pavlovicnemanja** [comment]
Wrong branch! Closed!

**Comment by ioanpocol** [comment]
I think that it is the right branch

**Comment by Aca-jov** [comment]
:+1:

**Comment by ioanpocol** [comment]
:+1:

**Comment by ioanpocol** [comment]
please rebase

**Comment by vied12** [comment]
This can't be done in CSS instead ?

**Comment by pavlovicnemanja** [comment]
@vied12 It can, but how to display it on output? On sending item, we are not sending CSS :)

**Comment by vied12** [comment]
From my point of view, provided content should be neutral in terms of style.
I think this is up to the view to add style to it where it will appear.
Because maybe everybody don't want (the same) indentation. This choice can also depends where you plan to show the text.

**Comment by pavlovicnemanja** [comment]
This is a convention on text formatting in Norway which is required by NTB customers. Here is description: https://dev.sourcefabric.org/browse/SDNTB-27

This is NTB request.

**Comment by ioanpocol** [comment]
I think we can add a setting and perform this indentation only if it is required by deployed instance.
You can add the setting on superdesk repo->  client/app/index.html
        config.features = {
            preview: 1,
            alchemy: 1
        };

**Comment by petrjasek** [comment]
@pavlovicnemanja afaik the idea was that they will add those spaces on output, and we only do some css to make it look like there are spaces

**Comment by vied12** [comment]
I don't believe we should hard code NTB's special convention in the Superdesk master branch.
To satisfy their needs, I would instead create a special filter on the Public Content API level that would customize the output for them.

I'm not a big fan for the settings solution neither. I don't think that we should save the style in the database at this step. And I believe that having too much settings and options will make the code harder to maintain and debug.

/ping @petrjasek and @hlmnrmr

**Comment by pavlovicnemanja** [comment]
First implementation was with pure CSS, just on frontend side... But after discussion on morning scrum with @petrjasek we agreed to add styles on element so it will be visible on output. Maybe I misunderstand something.

**Comment by petrjasek** [comment]
output updates should be handled by their system, so afaik we should not do any changes to content, just make it look like those spaces are there. and that css change should go into superdesk/superdesk ntb branch

**Comment by pavlovicnemanja** [comment]
Ok, so just to be clear, we should add this indentation without any changing of content (adding styles, adding classes...). So this will be visible only on frontend in our editor and preview.

Also, this acceptance criteria will be ignored:
"We should distinguish between the different "paragraph types" in the output format"

**Comment by vied12** [comment]
This is how I see it :)
And if they really need it in the output, the Content API should be in theory a better place for that

**Pull request merged**
