### PR TITLE
SDPA-139 : Superdesk doesn't pull in all images from the PA Images API

### PR DESCRIPTION
**Pull request by naomiaro**

### CODE REVIEW

**Comment by naomiaro** [comment]
created before, created after (etc) have been switched around and renamed created from and created until. 

- Had to previously read RTL to perform a range filter on these dates. (created after is start date, created before is end date)

**Comment by akintolga** [comment]
:+1:

**Comment by ioanpocol** [comment]
:+1:

**Comment by ioanpocol** [comment]
@naomiaro  Can be merged this PR?

**Pull request merged**
