### PR TITLE
fix(editor2): fix editor config defaults for toolbar

### PR DESCRIPTION
**Pull request by petrjasek**
and avoid some extra dict reseting

### CODE REVIEW

**Comment by naomiaro** [comment]
👍  thanks for this!

**Comment by actionless** [comment]
but it's still not reading it from `process.env`, right?

or we won't need to change that option on deployment?

**Comment by naomiaro** [comment]
yeah the template.js should be still updated to be `true` by default really

**Comment by petrjasek** [comment]
it shouldn't be changed on deployment

**Comment by actionless** [comment]
LGTM then

**Pull request merged**
