### PR TITLE
On switching the language from user s profile the hamburger menu still retains the previously set language unless relogin happens (SDESK 3057)

### PR DESCRIPTION
**Pull request by tomaskikutis**
SDESK-3057

### CODE REVIEW

**Comment by MarkLark86** [comment]
How does this go in terms of the performance of the site? Removing one way binding will add an Angular watch for each value, increasing the digest times each cycle.

**Comment by tomaskikutis** [comment]
I'll ask QA to test the performance. Most of the big lists use React, so I hope that there will not be too many watches at any given time.

**Comment by tomaskikutis** [comment]
There's little data on the master for QA to test, so I've checked myself on ansa test instance. I didn't notice any slowdown. A quick profiling didn't show clear differences between flamegraphs either.

**Comment by pablopunk** [comment]
If you're changing one-way bindings that means it was happening for all strings and not only the menu? Or it's just for consistency?

IMO if you change the language it should be "acceptable" to logout and login again, I'm guessing it's not a thing you do every day. But that's more of a decision for the product owner.

PS: I like your naming for the branch 😁

**Comment by tomaskikutis** [comment]
> If you're changing one-way bindings that means it was happening for all strings and not only the menu? Or it's just for consistency?

The only known place is the menu. Petr said one way bindings were put "just in case" not that there were any performance problems they solved. As we can see from the existence of the PR, they can cause issues and if removing them doesn't affect performance, it seems to me that's it's worth to get rid of them and remove a potencial source of bugs.

**Comment by petrjasek** [comment]
actually it shouldn't be problem outside the menu, at least not within ng-view because those parts will get reloaded when you will navigate from the user preferences, but the menu stays there hidden all the time, so it would be enough to fix it there.

**Comment by tomaskikutis** [comment]
I thought about the risks again and decided to go with a simpler approach of simply reloading the page. Not because of performance issues, but mostly due to the possibility that there might be places where business logic implicitly relies upon data not updating.

Will continue here https://github.com/superdesk/superdesk-client-core/pull/2404

**Pull request closed without merging**
