### PR TITLE
[SD-5001] - Separation of parameters, filters and saved panels in global search

### PR DESCRIPTION
**Pull request by akintolga**
- [x] Separate parameters section to its own tab in global search
- [x] Queries with aggregations will run only when the filters panel is opened
- [x] Reduce the query timeout from 3 sec to 300 msec
- [x] Re-arrange controls in parameters tab
- [x] Add Company Codes to the parameters
- [x] Change category and company code from `q` to `params` in query
- [x] Search from parameters will run only when `Search` button is clicked
- [x] Fix e2e tests

### CODE REVIEW

**Comment by akintolga** [comment]
@petrjasek created a new branch `newsearch` for this PR to be merged. The new instance `newsearch.dev.superdesk.org` hasn't been created automatically so I think someone needs to do that.

**Comment by mugurrus** [comment]
Quite a long read, hope I didn't miss anything :)
:+1:

**Comment by petrjasek** [comment]
:+1:

**Comment by petrjasek** [comment]
@akintolga it's there as https://ccnewsearch.dev.superdesk.org/ - it adds `cc` prefix for client core branches

**Pull request merged**
