### PR TITLE
[SD-4681]: report appropriate error when content profile name is not unique

### PR DESCRIPTION
**Pull request by gbbr**
Fixes issue [SD-4681](https://dev.sourcefabric.org/browse/SD-4681).

### CODE REVIEW

**Comment by akintolga** [comment]
:+1:

**Comment by sjunaid** [comment]
:+1:

**Comment by gbbr** [comment]
Not sure if the behavioral test failure is related to this PR 🍂

**Comment by petrjasek** [comment]
don't think so

**Pull request merged**
