### PR TITLE
SD-5078 : Display a proper error message in case a wrong GUID is ente…

### PR DESCRIPTION
**Pull request by naomiaro**
…red in product test section

### CODE REVIEW

**Comment by gbbr** [comment]
This is good. I'm only wondering if all the other stuff in the `response` object is irrelevant to debugging and if `_message` property will always be there. Otherwise, LGTM

**Comment by naomiaro** [comment]
I think it's always there, I can add a check for if message I guess. The message is the only thing that needs to be flashed to the user.

**Comment by gbbr** [comment]
As you think, thanks for explaining 👍

**Comment by petrjasek** [comment]
:+1:

**Comment by gbbr** [comment]
👍

**Comment by mdhaman** [comment]
:+1:

**Pull request merged**
