### PR TITLE
Update date picker

### PR DESCRIPTION
**Pull request by thecalcc**
SDBELGA-819

### CODE REVIEW

**Review by tomaskikutis — APPROVED** [review]

**Comment by thecalcc** [comment]
spellchecker failing

**Comment by tomaskikutis** [comment]
> spellchecker failing

You can ignore it for this PR. I pinged Petr so he reviews my fixes for those unit tests.

**Comment by thecalcc** [comment]
> > spellchecker failing
> 
> You can ignore it for this PR. I pinged Petr so he reviews my fixes for those unit tests.

Ok so all good to be merged? I see e2e also failing

**Comment by tomaskikutis** [comment]
e2e does need to pass. It might not be your PR breaking this, but take a look anyway

**Comment by tomaskikutis** [comment]
I just merged the PR that fixes CI to develop, so if you update from develop your PR should pass too

**Pull request merged**
