### PR TITLE
fix macros test

### PR DESCRIPTION
**Pull request by tomaskikutis**

### CODE REVIEW

**Comment by tomaskikutis** [comment]
Petr said he added some macros on the server. Previously, there probably weren't any groups so the list was being displayed ungrouped.

**Comment by pablopunk** [comment]
Yeah I heard it, I asked this before the scrum 👍

**Comment by petrjasek** [comment]
fyi the groups are gone (and will be gone by default)

**Comment by tomaskikutis** [comment]
Why? They seemed helpful when there are >10 macros. Should I close the PR then if we are getting rid of grouping?

**Comment by petrjasek** [comment]
by default all those macros are not enabled, but the groups will be there if needed

**Comment by tomaskikutis** [comment]
so if I closed this PR and restarted the tests on other PRs it should now pass since grouping will no longer be enabled by default?

**Comment by petrjasek** [comment]
that's right

**Pull request closed without merging**
