### PR TITLE
[sd-4037]-(fix) - For long saved search list in monitoring settings '…

### PR DESCRIPTION
**Pull request by sjunaid**
…next' and 'done' buttons are not visible

### CODE REVIEW

**Comment by mugurrus** [comment]
:+1:

**Comment by petrjasek** [comment]
I think the issue is that it's all in modal header, it's missing a closing `</div>` in `aggregate-settings.html` file

**Comment by sjunaid** [comment]
@petrjasek , true! , Thanks.

**Comment by ioanpocol** [comment]
:+1:

**Pull request merged**
