### PR TITLE
Omit invalid translations on the server before returning the JSON to the client. [SDCP-187]

### PR DESCRIPTION
**Pull request by GyanP**

### CODE REVIEW

**Comment by petrjasek** [comment]
that's file generated on transifex but then it's stored as part of client core and fetched by client when user changes language

**Comment by tomaskikutis** [comment]
How does it get here from transifex? We need a convenient place to do processing on it to remove invalid translations.

**Comment by petrjasek** [comment]
there is this `nggettext_compile` grunt task which creates json from po

**Comment by tomaskikutis** [comment]
@GyanP can you add code in that grunt task to automatically strip out invalid translations so they don't get to JSON?

**Comment by petrjasek** [comment]
will merge it as I need it for the release, lets make that check in another PR

**Pull request merged**
