### PR TITLE
Refactor to split authoring component into multiple files.

### PR DESCRIPTION
**Pull request by gbbr**
`authoring.js` was a really big file (>100KB), causing issues with maintenance and Webpack optimisations. This has now been split up. 

`authoring.js` becomes a folder `scripts/superdesk-authoring/authoring/` that looks like this:

```sh
$ tree . --dirsfirst
.
├── controllers
│   ├── AuthoringController.js
│   ├── ChangeImageController.js
│   └── index.js
├── directives
│   ├── ArticleEditDirective.js
│   ├── AuthoringContainerDirective.js
│   ├── AuthoringDirective.js
│   ├── AuthoringEmbeddedDirective.js
│   ├── AuthoringHeaderDirective.js
│   ├── AuthoringTopbarDirective.js
│   ├── CharacterCount.js
│   ├── DashboardCard.js
│   ├── FullPreviewDirective.js
│   ├── Html5vfix.js
│   ├── ItemAssociationDirective.js
│   ├── PreviewFormattedDirective.js
│   ├── RemoveTagsDirective.js
│   ├── SendItem.js
│   ├── ThemeSelectDirective.js
│   ├── WordCount.js
│   └── index.js
├── filters
│   └── index.js
├── services
│   ├── AuthoringService.js
│   ├── AuthoringThemesService.js
│   ├── AuthoringWorkspaceService.js
│   ├── AutosaveService.js
│   ├── ConfirmDirtyService.js
│   ├── HistoryFactory.js
│   ├── LockService.js
│   ├── RenditionsService.js
│   └── index.js
├── authoring.spec.js
├── helpers.js
└── index.js

### CODE REVIEW

**Comment by petrjasek** [comment]
I'm not sure I like type based structure, but lets see what others think about it

**Comment by gbbr** [comment]
I'm fine with any approach, as long as we split it up. What were you thinking?

**Comment by gbbr** [comment]
More input from Slack:
```

Petr Jasek [2:25 PM]  
yep I would prefer grouping by feature

Petr Jasek [2:25]  
which would be hard atm

Gabriel Aszalos [2:26 PM]  
This is technically the authoring feature. If we divide into even smaller parts, that will take a lot longer.

Petr Jasek [2:26 PM]  
yep

Gabriel Aszalos [2:26 PM]  
But I see what you mean. Maybe each activity could be a “feature”. There are 7 in authoring

Gabriel Aszalos [2:27]  
This might still serve as an improvement

Petr Jasek [2:27 PM]  
yep I would merge it but also start thinking about the structure
```

**Comment by thnkloud9** [comment]
:thumbsup: - I am ok with this structure ;-)

**Pull request merged**
