### PR TITLE
sync user login/logout status on master desk

### PR DESCRIPTION
**Pull request by petrjasek**
SDESK-5817

uses https://github.com/superdesk/superdesk-core/pull/2199

### CODE REVIEW

**Review by pavlovicnemanja — APPROVED** [review]

**Comment by tomaskikutis** [comment]
Does this only affect user avatar component? If so, it'd be better to handle it there.

**Comment by petrjasek** [comment]
it does, but this is rather about the state which should be imo higher than in the avatar component, we can have same user on many desks and there is no need to refetch the user more than once

**Comment by tomaskikutis** [comment]
I agree that re-fetching data multiple times for the same user is not good. But handling this in every parent component that renders user avatar isn't a good solution either.

Ideally, there would be a central data store that would handle such updates. Since we don't have it yet, what about putting a short-lived cache object inside user avatar component? It would avoid fetching the same user multiple times and would allow moving the code to user avatar component instead of putting it everywhere where avatar is used.

**Comment by petrjasek** [comment]
will think about it, but would rather put there some initial store than complicate the components which should be using it.

**Comment by tomaskikutis** [comment]
I actually meant to put the cache object, not in the component, but at the file level. Something simple like

```
var cache = {};

function getUser(id) {
    if (cache[id] != null) {
        return Promise.resolve(cache[id]);
    } else {
        fetch(...).then((res) => {
            cache[id] = res;

            return res;
        })
    }
}
```

Initial store would work too.

**Comment by petrjasek** [comment]
and what about the listener? that would be defined on each component?

**Comment by petrjasek** [comment]
@tomaskikutis I would rather leave it as it is now, there are like 1500 instances on cp of that user avatar component so don't want to complicate that one

**Comment by tomaskikutis** [comment]
> there are like 1500 instances on cp of that user avatar component

Good, that means that you would fix the issue in all places, not only in 1/1500. ;)

To me, addressing it, seems an easy choice:
* Current implementation isn't clean - it violates separation of concerns and introduces undesirable coupling. (master desk should be ignorant of how avatar component works and not try to affect it)
* The fix is only available in one place
* It's relatively easy to implement it right. I wouldn't say adding a cache object is either risky or adds much coupling, so it doesn't seem like a complication to me.

**Comment by petrjasek** [comment]
I mean there are 1500 avatar components rendered at the same time, and with this approach it's handled for all in 1 place.
and while now it's only checking the update status of the user, in general it should keep user info fresh because that's what master desk is showing, so imo it's not violating separation of concerns

**Review by tomaskikutis — APPROVED** [review]

**Pull request merged**
