### PR TITLE
Analytics

### PR DESCRIPTION
**Pull request by ancafarcas**

### CODE REVIEW

**Comment by petrjasek** [comment]
seems like this analytics e2e test is broken https://test.superdesk.org/logs/sdcpr-1258/fd084b3513/20170118-132216/check-e2e--part1.log.htm

**Comment by ancafarcas** [comment]
The test is failing because the used back-end  is not up to date, apparently. Though, the last added fields are now available (PR was merged yesterday).

**Comment by petrjasek** [comment]
@ancafarcas yep update `test-server/requirements.txt` to use that updated server-core version

**Comment by ancafarcas** [comment]
Thanks @petrjasek !

**Pull request merged**
