### PR TITLE
[SD-5368]- Update page title with the Url and Desk/Workspace

### PR DESCRIPTION
**Pull request by akintolga**
- A new service is created to update the page title
- The title will be 'Superdesk {- Url} {-Desk/Workspace}
- Url can be:
 - Dashboard, Monitoring, Spike, Highlights, Search, Settings
- If Url is search then there won't be desk

### CODE REVIEW

**Comment by petrjasek** [comment]
:+1:

**Comment by mdhaman** [comment]
:+1:

**Comment by mugurrus** [comment]
:+1:

**Comment by ioanpocol** [comment]
Please rebase

**Pull request merged**
