### PR TITLE
updated superdesk-ui-framework to 2.4.18

### PR DESCRIPTION
**Pull request by dev-tsoni**

### CODE REVIEW

**Comment by petrjasek** [comment]
is this related to any ticket @dev-tsoni ?

**Comment by dev-tsoni** [comment]
> is this related to any ticket @dev-tsoni ?

No, just for a test instance for working sams 3 dots issue.

**Comment by MarkLark86** [comment]
@petrjasek This is for ticket SDESK-6226

**Comment by MarkLark86** [comment]
Already pushed into `develop` and `hotfix/2.4.1`

**Pull request closed without merging**
