### PR TITLE
Edit crop view: show only renditions based on ratio SDPA-396

### PR DESCRIPTION
**Pull request by vied12**

### CODE REVIEW

**Comment by petrjasek** [comment]
:+1:

**Comment by ioanpocol** [comment]
:+1:

**Comment by vied12** [comment]
Just added a commit in order to avoid repetition.
Can you please check it out ?
@petrjasek @ioanpocol

**Comment by ioanpocol** [comment]
:+1:

**Comment by petrjasek** [comment]
:+1:

**Pull request merged**
