### PR TITLE
run e2e tests on travis

### PR DESCRIPTION
**Pull request by petrjasek**
btw - tests might fail ;)
not sure we should try to fix it here, I have another PR (with react) fixing most of them..

### CODE REVIEW

**Comment by ioanpocol** [comment]
:+1: 
Let's see if the tests will start.

**Comment by akintolga** [comment]
:+1:

**Comment by petrjasek** [comment]
@ioanpocol why rebase?

**Comment by ioanpocol** [comment]
Some e2e tests were failing and it should be fixed if you rebase.

**Comment by petrjasek** [comment]
yep but still this wasn't supposed to fix it, just to run it..

**Comment by ioanpocol** [comment]
ok

**Comment by petrjasek** [comment]
so this should get merged and the other prs should be rebased imo, not the other way around..

**Comment by ioanpocol** [comment]
It will help if we split again the tests in 3 build jobs for e2e tests and another one for code style and unit tests

**Comment by ioanpocol** [comment]
Should we stop running all e2e tests on superdesk repo?

**Comment by ioanpocol** [comment]
I will disable e2e tests that are failing after merging this PR

**Pull request merged**
