### PR TITLE
Don't close preview pane when spiking/unspiking random items.

### PR DESCRIPTION
**Pull request by gbbr**
Fixes JIRA issue [SD-4366](https://dev.sourcefabric.org/browse/SD-4366).

### CODE REVIEW

**Comment by petrjasek** [comment]
:+1:

**Comment by gbbr** [comment]
Thanks for reviewing @petrjasek - I have no merge rights, so you'll have to do it yourself

**Comment by petrjasek** [comment]
no worries, it needs one more review, and travis to say it's ok :wink:

**Comment by mugurrus** [comment]
:+1:

**Pull request merged**
