### PR TITLE
test extensions build on github actions

### PR DESCRIPTION
**Pull request by petrjasek**

### CODE REVIEW

**Review by tomaskikutis — COMMENTED** [review]
We're already compiling extensions as a part of the main CI task.

```
// package.json scripts
"test": "npm run lint && npm run unit && node tasks/verify-client-api-changes.js",
                                         ^
```

**Comment by petrjasek** [comment]
interesting, because we have it failing here
https://github.com/superdesk/superdesk/actions/runs/12028429253/job/33531537951?pr=3508

**Comment by tomaskikutis** [comment]
It's most likely because of cherry-picking one thing which depended on another and that another wasn't cherry picked.

In this case I see that it's crashing due to changes in ui-framework, not due to API changes.

**Comment by petrjasek** [comment]
yep looks like it

**Pull request closed without merging**
