### PR TITLE
SD-5178 : Change in dateline value doesn't trigger save

### PR DESCRIPTION
**Pull request by naomiaro**

### CODE REVIEW

**Comment by akintolga** [comment]
:+1:

**Comment by mdhaman** [comment]
:+1: @naomiaro User profile also uses Dateline. Can please you verify if it is still working properly?

**Comment by naomiaro** [comment]
@mdhaman yep user profile is fine, it was using totally different code from this.

**Comment by naomiaro** [comment]
Looks like this still needs something else, save is only appearing sometimes.

**Comment by naomiaro** [comment]
The problems have to do with autosaving https://github.com/superdesk/superdesk-client-core/pull/792 this should fix it I think.

**Pull request merged**
