### PR TITLE
[SDESK-1109] - If saving "area of interest" operation fails then cont…

### PR DESCRIPTION
**Pull request by MarkLark86**
…inuous spinner is displayed

### CODE REVIEW

**Comment by gbbr** [comment]
CI is throwing an error about some dependency missing...

**Comment by petrjasek** [comment]
rebasing now should fix it

**Comment by naspeh** [comment]
trick `fire:check-npmtest` fixed by http://test.superdesk.org/sdc/pull/1513/restart?t=build,check-npmtest without rebase :)

`t=build` is needed to restart `fire:build`...

**Comment by naspeh** [comment]
Travis was fixed also just by restarting: https://travis-ci.org/superdesk/superdesk-client-core/builds/221623256 :)

But @MarkLark86 have done rebasing already

**Pull request merged**
