### PR TITLE
(feat)[SDESK-745] Adding product types to products.

### PR DESCRIPTION
**Pull request by mdhaman**
depends on https://github.com/superdesk/superdesk-core/pull/832

### CODE REVIEW

**Comment by mdhaman** [comment]
@hlmnrmr we are not able to see the latest changes in the test instance.

**Comment by naspeh** [comment]
@mdhaman the instance is fixed now

**Comment by mdhaman** [comment]
@naspeh thanks.

**Comment by ioanpocol** [comment]
Please rebase in order to pass the tests

**Comment by mdhaman** [comment]
@hlmnrmr default value is `both`. It should not affect the existing installation i.e.  But still you need to run the `data:upgrade` command to insert `product_types` vocabularies for product maintenance.

**Pull request merged**
