### PR TITLE
make sports default desk in e2e tests

### PR DESCRIPTION
**Pull request by tomaskikutis**

### CODE REVIEW

**Comment by tomaskikutis** [comment]
Hi @petrjasek I found tests fail here due to an issue with restoring database records. Could you look and see if you could fix it?

I tracked down the issue from seeing that tests were trying to interacted with locked articles - when they shouldn't be locked. I found later that they're locked due to DB record not being restored before the test.

```
# restoring main record - all good
curl -X POST http://localhost:5000/api/restore_record -H "Content-Type: application/json" --data '{"name": "main"}'
{"name": "main", "_updated": "2024-08-05T15:47:27+0000", "_created": "2024-08-05T15:47:27+0000", "_etag": "b8dcd3eb08eea4b38486ea54ecf789c3d8359276", "_id": "OK", "_links": {"self": {"title": "Restore_record", "href": "restore_record/OK"}}, "_status": "OK"}

# restoring spellchecker record - all good
curl -X POST http://localhost:5000/api/restore_record -H "Content-Type: application/json" --data '{"name": "spellchecker"}'
{"name": "spellchecker", "_updated": "2024-08-05T15:47:39+0000", "_created": "2024-08-05T15:47:39+0000", "_etag": "c65af64fb7e5180adbe9f07ad763364ff7a0f35e", "_id": "OK", "_links": {"self": {"title": "Restore_record", "href": "restore_record/OK"}}, "_status": "OK"}

# restoring spellchecker record again - crashes
curl -X POST http://localhost:5000/api/restore_record -H "Content-Type: application/json" --data '{"name": "spellchecker"}'
<html>
  <head>
    <title>Internal Server Error</title>
  </head>
  <body>
    <h1><p>Internal Server Error</p></h1>
    
  </body>
</html>
```

Here are the server logs:

```
server-1   | 15:52:39 rest.1 | INFO:superdesk.timer:restore_record: 1176.215ms
server-1   | 15:52:41 rest.1 | [i]  restoring record from 2024-05-08T12:48:47.957205
server-1   | 15:52:41 rest.1 | 
server-1   | 15:52:41 rest.1 | 📼▶ restoring record dump/records/spellchecker.json.bz2
server-1   | 15:52:41 rest.1 | updated doc ObjectId('65ae379f77677941642bb478') in 'auth'
server-1   | 15:52:41 rest.1 | updated doc ObjectId('655494d8dfb36babb9663383') in 'users'
server-1   | 15:52:41 rest.1 | ERROR:superdesk.commands.data_manipulation:🔥 Oh no, something bad happened
server-1   | 15:52:41 rest.1 | Traceback (most recent call last):
server-1   | 15:52:41 rest.1 |   File "/opt/venv/lib/python3.10/site-packages/superdesk/commands/data_manipulation.py", line 696, in run
server-1   | 15:52:41 rest.1 |     collection.insert(doc)
server-1   | 15:52:41 rest.1 |   File "/opt/venv/lib/python3.10/site-packages/pymongo/collection.py", line 3293, in insert
server-1   | 15:52:41 rest.1 |     return self._insert(doc_or_docs, not continue_on_error,
server-1   | 15:52:41 rest.1 |   File "/opt/venv/lib/python3.10/site-packages/pymongo/collection.py", line 613, in _insert
server-1   | 15:52:41 rest.1 |     return self._insert_one(
server-1   | 15:52:41 rest.1 |   File "/opt/venv/lib/python3.10/site-packages/pymongo/collection.py", line 602, in _insert_one
server-1   | 15:52:41 rest.1 |     self.__database.client._retryable_write(
server-1   | 15:52:41 rest.1 |   File "/opt/venv/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1498, in _retryable_write
server-1   | 15:52:41 rest.1 |     return self._retry_with_session(retryable, func, s, None)
server-1   | 15:52:41 rest.1 |   File "/opt/venv/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1384, in _retry_with_session
server-1   | 15:52:41 rest.1 |     return self._retry_internal(retryable, func, session, bulk)
server-1   | 15:52:41 rest.1 |   File "/opt/venv/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1416, in _retry_internal
server-1   | 15:52:41 rest.1 |     return func(session, sock_info, retryable)
server-1   | 15:52:41 rest.1 |   File "/opt/venv/lib/python3.10/site-packages/pymongo/collection.py", line 600, in _insert_command
server-1   | 15:52:41 rest.1 |     _check_write_command_response(result)
server-1   | 15:52:41 rest.1 |   File "/opt/venv/lib/python3.10/site-packages/pymongo/helpers.py", line 226, in _check_write_command_response
server-1   | 15:52:41 rest.1 |     _raise_last_write_error(write_errors)
server-1   | 15:52:41 rest.1 |   File "/opt/venv/lib/python3.10/site-packages/pymongo/helpers.py", line 207, in _raise_last_write_error
server-1   | 15:52:41 rest.1 |     raise DuplicateKeyError(error.get("errmsg"), 11000, error)
server-1   | 15:52:41 rest.1 | pymongo.errors.DuplicateKeyError: E11000 duplicate key error collection: superdesk_e2e.dictionaries index: _id_ dup key: { _id: ObjectId('663b74c42aca234bf2898eda') }, full error: {'index': 0, 'code': 11000, 'keyPattern': {'_id': 1}, 'keyValue': {'_id': ObjectId('663b74c42aca234bf2898eda')}, 'errmsg': "E11000 duplicate key error collection: superdesk_e2e.dictionaries index: _id_ dup key: { _id: ObjectId('663b74c42aca234bf2898eda') }"}
```

**Comment by tomaskikutis** [comment]
FYI the `spellchecker` record is based on `main` record and I did update `main` on this PR. It shouldn't be a problem I think. Again, all works fine on first restore.

**Comment by petrjasek** [comment]
will check

**Comment by tomaskikutis** [comment]
@petrjasek did you fix this one yet?

**Comment by petrjasek** [comment]
not yet

**Comment by tomaskikutis** [comment]
It'd be good if you could look into it next week. Without merging this, we can't modify the main test DB snapshot. We will likely need to do soon for other tests.

**Comment by petrjasek** [comment]
seems like that `spellchecker` dump didn't refer to any base dump, so it wasn't resetting db before applying it and then there were conflicts

**Comment by tomaskikutis** [comment]
Interesting. It shouldn't be possible to make a record that wouldn't be based on a dump? Do you think it's a recording bug or error caused by user executing commands while trying to make a record?

**Comment by petrjasek** [comment]
seems like it's possible currently,  that base dump is not mandatory when creating a record

**Review by petrjasek — APPROVED** [review]

**Pull request merged**
