### PR TITLE
Media upload drop downs UI issue

### PR DESCRIPTION
**Pull request by dzonidoo**
SDANSA-510

### CODE REVIEW

**Review by tomaskikutis — APPROVED** [review]
check if you're not breaking it in other places where this component is used which might be using light theme

**Comment by dzonidoo** [comment]
I already checked

**Comment by tomaskikutis** [comment]
all good then

**Comment by tomaskikutis** [comment]
actually not, you need to fix CI :D

**Comment by tomaskikutis** [comment]
or no, actualy you don't - it's already broken there - not caused by your PR

**Comment by dzonidoo** [comment]
so i can merge it? right?

**Comment by tomaskikutis** [comment]
yep

**Pull request merged**
