### PR TITLE
[sd-4173]-(Imp)- Icons needed for highlight and take packages

### PR DESCRIPTION
**Pull request by sjunaid**

### CODE REVIEW

**Comment by petrjasek** [comment]
can we rather store 'highlights' or 'takes' into package 'profile' field? and make use of that value for icon. because this will need yet another set of ifs when we introduce another package type..

**Comment by akintolga** [comment]
I agree with you @petrjasek. If it is possible we want to merge like this for the time being but create a new ticket to:
- Refactor the backend to use either `profile` or `package_type` across the board to identify the type of the (composite) item
- Refactor client to handle server side changes

**Comment by petrjasek** [comment]
:+1: sounds like a plan

**Comment by mdhaman** [comment]
:+1:

**Pull request merged**
