### PR TITLE
Z index property

### PR DESCRIPTION
**Pull request by dzonidoo**
SDESK-6952

### CODE REVIEW

**Review by tomaskikutis — APPROVED** [review]
don't merge it yet

**Comment by tomaskikutis** [comment]
Let's wait until 2.7 is released and only merge it afterwards

**Comment by petrjasek** [comment]
do we need this one still @dzonidoo ?

**Comment by tomaskikutis** [comment]
We do. At the time we were planning to do a release so I didn't want to push code that is likely to break things. Do you think Petr now is a good time? Do we have any releases planned soon?

**Comment by petrjasek** [comment]
now it should be fine, there is already a branch for 2.8 so there is time before there will be any release from develop

**Comment by tomaskikutis** [comment]
@dzonidoo then update the branch and merge it

**Pull request closed without merging**
