### PR TITLE
fix e2e server requirements

### PR DESCRIPTION
**Pull request by petrjasek**

### CODE REVIEW

**Review by dzonidoo — APPROVED** [review]

**Comment by petrjasek** [comment]
can't reproduce those failing e2e tests locally, any idea what might be wrong here @tomaskikutis ?

**Comment by tomaskikutis** [comment]
No idea. Maybe chrome driver updated again? :laughing: There was one test that was randomly failing from time to time, but it's not it this time. I'll check it out.

**Comment by petrjasek** [comment]
I don't know, have the same chromedriver version locally, but an updated chrome, will probably let it rest a bit

**Comment by tomaskikutis** [comment]
image
I've found a clue in screenshots, list fails to load for some reason. I couldn't reproduce it, but will try to match versions on my local machine to what github uses

**Comment by tomaskikutis** [comment]
I ran e2e with chrome 116, launched the server with docker, ran `docker-compose build --no-cache` to ensure latest server code, built client for production and still can't reproduce it. I'll added outputting of browser console errors, hopefully we can see something there.

**Pull request merged**
