### PR TITLE
"SERVICE" in editor renamed to "CATEGORY"

### PR DESCRIPTION
**Pull request by eozan**
SD-5121

### CODE REVIEW

**Comment by ahilles107** [comment]
Finally! Thank You @eozan!

**Comment by akintolga** [comment]
@eozan would you please check if NTB requires this field to be named as 'Service'. If that is the case you need to add translation item for them if it doesn't exist. Thanks in advance.

**Comment by ioanpocol** [comment]
For NTB the field name is Service

**Comment by eozan** [comment]
@akintolga Another pull request is made for NTB translations: https://github.com/superdesk/superdesk/pull/2216

**Comment by mugurrus** [comment]
:+1:

**Pull request merged**
