### PR TITLE
As a user I want to be notified when a story is marked for me. (SDBELGA-124)

### PR DESCRIPTION
**Pull request by GyanP**
Requires https://github.com/superdesk/superdesk-core/pull/1634

### CODE REVIEW

**Comment by tomaskikutis** [comment]
All features related to "mark for user" should go to `scripts/extensions/markForUser`. There's no extension point for notifications yet, so it will need to be added.

**Comment by tomaskikutis** [comment]
Here's an addition to client API I came up with. An extension would indicate notification IDs it wants to handle and action buttons it wants to provide. It wouldn't provide the buttons themselves, but only a label and `onClick` handler function so API surface is smaller. Feel free to add suggestions @petrjasek @pablopunk 

screenshot_3

**Comment by pablopunk** [comment]
@tomaskikutis sounds good, I'm guessing it should also require a payload to include some data about the notification

**Comment by tomaskikutis** [comment]
Yep, we could add an argument to the click handler so it's `onClick(notification)`. The notification text will come from the server, so we don't need to handle that here. Unless we discover that we need it when implementing then we could adjust the interface.

**Comment by pablopunk** [comment]
is this gonna be an extension?

**Pull request closed without merging**
