### PR TITLE
[SD-4254][SD-4253] - Disable send to and package for locked items

### PR DESCRIPTION
**Pull request by akintolga**
This change is for multi selections...

### CODE REVIEW

**Comment by mugurrus** [comment]
:+1:

**Comment by sjunaid** [comment]
:+1:

**Comment by mdhaman** [comment]
:+1:

**Comment by petrjasek** [comment]
working on a similar issue, with a different approach.
https://github.com/superdesk/superdesk-client-core/pull/439

**Comment by akintolga** [comment]
I'll wait until #439 is merged and update this PR...

**Comment by ioanpocol** [comment]
:+1:

**Pull request merged**
