### PR TITLE
update mark_for_user notification perefrence name [SDBELGA-818]

### PR DESCRIPTION
**Pull request by devketanpro**

### CODE REVIEW

**Review by thecalcc — APPROVED** [review]

**Review by tomaskikutis — CHANGES_REQUESTED** [review]
let me think a bit before we merge this

**Comment by thecalcc** [comment]
@tomaskikutis backend related changes

**Comment by tomaskikutis** [comment]
The way I think it should be, is that we have 1 notification. Let's say "mark for user" and the extension exposes only that. On client-core side, in settings we could manage whether we want to receive only email, only in-app. The extension should only expose that a notification exists and client core would take care of via which channels it should be sent.

Could we register it as a single notification instead of 3?

What do you think @petrjasek

**Comment by petrjasek** [comment]
yep that makes sense, maybe it should be more like:
```ts
{
    name: 'mark_for_user',
    label: '...',
    email: true,
    desktop: true,
}
```

**Comment by tomaskikutis** [comment]
What would `email, desktop` options mean? Whether a particular channel is available to be chosen in settings? When wouldn't it be possible?

**Comment by petrjasek** [comment]
yep, but not sure actually if there would be any where only 1 makes sense

**Comment by tomaskikutis** [comment]
I'd say let's go without them and we will expand the API if we ever need it in the future.

**Comment by thecalcc** [comment]
> I'd say let's go without them and we will expand the API if we ever need it in the future.

Don't we need it now in order for disable all desk notifications to work?

**Comment by tomaskikutis** [comment]
No. Extension will provide the id/label of a notification and then it's up for the core code to display notification delivery options.

**Comment by tomaskikutis** [comment]
@petrjasek could you guide @devketanpro on how to adjust the back-end so we support registering a single notification and are able to deliver it using different channels? Or do you think we can't do it that easily and would need to still use 2 notifications on the back-end?

**Comment by petrjasek** [comment]
so how would we store it in preferences, under single `notifications` object like:
```ts
{"notifications": {"mark_for_user": {"email": false, "desktop" true}}}
```
?

**Comment by tomaskikutis** [comment]
Yep, the one you proposed would do.

**Comment by petrjasek** [comment]
ok will do the backend changes

**Comment by petrjasek** [comment]
btw there is this websocket notification for the extension, that should be sent no matter what's the user preference right?

**Comment by tomaskikutis** [comment]
Websocket message about a new notification? No point to send it if desktop notification is disabled. If technically difficult to not send it, we can continue sending and simply not show it on the client.

**Comment by petrjasek** [comment]
seems like there is `item:marked` and `item:unmarked` sent, so I'm wondering if that's needed for some UI refreshing or it's used only for desktop notifications

**Comment by tomaskikutis** [comment]
`'item:marked'` is used to check if re-fetching needs to happen so we'll have to keep it for now as we don't have any alternative way to get notified. websockets come close, but they don't provide values, only field names.

**Comment by tomaskikutis** [comment]
> websockets come close, but they don't provide values, only field names.

I meant the generic `resouce:update` message

**Comment by petrjasek** [comment]
btw would the UI handle undefined values as enabled?

**Comment by tomaskikutis** [comment]
At the moment I see it doesn't check message payload at all - since we now have 2 different notifications for marked/unmarked. If we change it, we'll have to adjust the code a bit and we'd be able to apply a default too.

**Comment by petrjasek** [comment]
did the backend changes in https://github.com/superdesk/superdesk-core/pull/2652, can you handle the frontend @tomaskikutis @thecalcc ?

**Pull request closed without merging**
