### PR TITLE
SD-4394 -- Remove afterClose function for macros

### PR DESCRIPTION
**Pull request by vied12**
It was causing an unwanted redo in the editor

It reverts partially #363, (@eozan if you can check please)

cc @ioanpocol

### CODE REVIEW

**Comment by eozan** [comment]
this breaks other fixes for both pa and aap :-1:

**Comment by vied12** [comment]
Maybe @mdhaman has an idea about how we can solve this issue

**Comment by mdhaman** [comment]
@vied12 , @eozan there were 2 problems:
1) If you open versions widget and go to previous version it shows previous version in readonly mode in the editor. If you close the versions widget you still see previous version of the item in readonly mode and only option left was to close editor.
2) Close the macro widget tab after macro is applied. 

What is the issue over here?

**Comment by mdhaman** [comment]
@vied12 do we need this still?

**Comment by vied12** [comment]
it seems that the initial problem has been solved. Thanks

**Pull request closed without merging**
