### PR TITLE
LBSD-1000 Blog formatting is not saved

### PR DESCRIPTION
**Pull request by vladnicoara**
when editing some contend and only changing markup( making things bold or italic for example), the changes can't be saved

### CODE REVIEW

**Comment by gbbr** [comment]
There are some failing tests. I'm not sure if they are related to your changes (probably not), but I've restarted the build.

**Comment by gbbr** [comment]
Please rebase this.

**Comment by gbbr** [comment]
Rebase this PR to get a clean build...

**Comment by petrjasek** [comment]
had to revert this, will redo this one in a new PR

**Pull request merged**
