### PR TITLE
FIX: Issues with the list in Spike view [SDESK-5923]

### PR DESCRIPTION
**Pull request by GyanP**

### CODE REVIEW

**Comment by petrjasek** [comment]
can you pls explain how does it fix it? it seems to be it should reload even more now

**Comment by GyanP** [comment]
> can you pls explain how does it fix it? it seems to be it should reload even more now

We were getting the value in decimal and we are checking for the exact value, for example, we were getting the scroll height as 2497 but offset + scrollTop 2497.385 something like that, so that's why I have to make it round off.

**Comment by petrjasek** [comment]
I mean it will call this `this.loadMore();` more often right? because it wasn't matching without rounding. now with rounding that `reachedBottom` can be actually true

**Comment by GyanP** [comment]
> I mean it will call this `this.loadMore();` more often right? because it wasn't matching without rounding. now with rounding that `reachedBottom` can be actually true

Ya right, it will call load more, if we reached the bottom and that's what's the issue specified in the ticket that **there was no pagination** so after this changes it will give us the pagination.

**Review by petrjasek — APPROVED** [review]

**Pull request merged**
