### PR TITLE
SDNTB-49 Show all available languages

### PR DESCRIPTION
**Pull request by vladnicoara**
Even if the translation isn't fully ready yet

### CODE REVIEW

**Comment by ioanpocol** [comment]
Peer verification superdesk PR:
https://github.com/superdesk/superdesk/pull/1824

**Comment by petrjasek** [comment]
:+1:

**Comment by ioanpocol** [comment]
please rebase

**Comment by ioanpocol** [comment]
@hlmnrmr Please grant to Vlad merge right

**Pull request merged**
