### PR TITLE
fix JSX formatting

### PR DESCRIPTION
**Pull request by tomaskikutis**
See added eslint rules: https://github.com/superdesk/superdesk-client-code-style/pull/6

### CODE REVIEW

**Comment by pablopunk** [comment]
The changes in the tests, the ones about the new error messages, do they belong to this PR?

I mean I have no issue with it, just asking in case you didn't know they were there by mistake.

**Comment by tomaskikutis** [comment]
There are no changes to tests in this PR except lint fixes in tests. I have squashed-merged `develop` to this branch and it looks like GitHub is not displaying changed files correctly. For example, I can see `publishing_spec.ts` in the list of changed files on GitHub, but if I merge this PR to develop without committing and grep `git status`, that file is not there.

**Comment by petrjasek** [comment]
I think squash merging is the problem, can you rather rebase it now? if you merge it it should know that those commits are already in develop, but when you squash it's a new commit with no reference there. while this might not be an issue on this PR I've seen it on others and there we might need to backport the changes which will add all the other unrelated changes

**Comment by tomaskikutis** [comment]
:+1: I've reset that merge commit and merged it without squashing now.

**Comment by tomaskikutis** [comment]
@petrjasek @pablopunk could you approve the PR if you don't have further comments? It would be good to not keep this open for too long to avoid merge conflicts.

**Review by pablopunk — APPROVED** [review]

**Review by petrjasek — APPROVED** [review]

**Pull request merged**
