### PR TITLE
[SD-4841]-(send_spec) - Optimize e2e tests by combining some of the t…

### PR DESCRIPTION
**Pull request by sjunaid**
…est cases

### CODE REVIEW

**Comment by akintolga** [comment]
:+1:

**Comment by mdhaman** [comment]
:+1:

**Comment by mugurrus** [comment]
:+1:

**Comment by gbbr** [comment]
One of the tests is broken...

**Comment by ioanpocol** [comment]
@sjunaid Please rebase the PR

**Comment by gbbr** [comment]
This is over a month old and it has not been updated, so I assume it's ok to close - please re-open the PR if it's still needed.

**Pull request closed without merging**
