### PR TITLE
Context menu not visible for nested events in narrow view

### PR DESCRIPTION
**Pull request by dzonidoo**
STT-94

### CODE REVIEW

**Review by thecalcc — APPROVED** [review]

**Comment by tomaskikutis** [comment]
What was causing the issue?

**Comment by dzonidoo** [comment]
@tomaskikutis 'div - wrappers' make a issue for grid layout

**Comment by tomaskikutis** [comment]
check if it still works well in other usages, those wrappers were probably added for a reason

**Comment by dzonidoo** [comment]
I dont see any issue with removing the extra div on browser. Would you like to have it put back? But need to be display contents...
My opinion is that we dont need 4 divs in a row in any case...

**Comment by tomaskikutis** [comment]
The same way adding a div can cause style issues, it might cause them if you remove it. I'm not saying not to remove it, but check other usages to ensure that removing doesn't break anything.

**Pull request merged**
