### PR TITLE
fix(products): Fixed issue with removing products after reverting version

### PR DESCRIPTION
**Pull request by pavlovicnemanja**
[SDANSA-331]

### CODE REVIEW

**Comment by tomaskikutis** [comment]
Can you describe what ended up being the issue?

**Comment by pavlovicnemanja** [comment]
@tomaskikutis when items were reverted, product objects are not filtered well with` _.without`, so it will falling back to `_.remove` by string, so I added here first to check if `term` is object and has `name` property so it can by removed with `_.remove` functionality.

**Comment by tomaskikutis** [comment]
Why was it failing using without? Can you add TypeScript types to the `MetaTermsDirective` so it's more clear? You can check the example on how to add types in `ItemCarouselDirective.ts`

**Comment by pavlovicnemanja** [comment]
Fields were not a problem, they were the same, I think problem was caused by `__proto__`.

**Comment by tomaskikutis** [comment]
What problems did `__proto__` cause?

**Comment by tomaskikutis** [comment]
:) yeah, I understand that the item wasn't being removed, but why do you think it's related to `__proto__` and in what way did it influence the `without` function?

**Comment by pavlovicnemanja** [comment]
That was only thing that was different in object. Because of that I thought that _.without function was not working. Can we move further discussion on slack channel? It's faster.

**Pull request merged**
