### PR TITLE
fix(time): make timestamps in list show non relative time

### PR DESCRIPTION
**Pull request by petrjasek**
it does only time for current day, day + time for current week,
month + day otherwise. + is configurable.

SD-4098

### CODE REVIEW

**Comment by ioanpocol** [comment]
:+1:

**Comment by naomiaro** [comment]
I think we need some kind of documentation for vars like config.longDateFormat or to put them all in template.js or index.html (for each client) just somewhere so we can quickly scan the list, see defaults (for tests & configuration). Otherwise it's sort of some wasted time trying to find what's currently done/available.

**Comment by akintolga** [comment]
:+1:

**Comment by petrjasek** [comment]
added docs to readme, @naomiaro wasn't sure about this model date/time format, doesn't seem like something that should be changed right?

**Comment by naomiaro** [comment]
:+1:  Thanks for the docs!

**Pull request merged**
