### PR TITLE
SDPA-268 : Display usage terms in image metadata

### PR DESCRIPTION
**Pull request by naomiaro**

### CODE REVIEW

**Comment by mdhaman** [comment]
:+1:

**Comment by eozan** [comment]
:+1:

**Comment by vied12** [comment]
`usageterms` was already shown here https://github.com/naomiaro/superdesk-client-core/blob/ae661e0461061516cada9ae868cd34cf4e3a85fc/scripts/superdesk-archive/views/metadata-view.html#L164-L166
it was duplicated at the top of the list on purpose ?

**Comment by naomiaro** [comment]
@vied12 ah, I took this ticket and didn't realize it was already done... didn't notice that.

**Pull request merged**
