### PR TITLE
add coding conventions

### PR DESCRIPTION
**Pull request by tomaskikutis**

### CODE REVIEW

**Comment by petrjasek** [comment]
imo this should be in the root folder, called [contributing](https://github.com/blog/1184-contributing-guidelines)

**Comment by pablopunk** [comment]
I agree with @petrjasek, `/contributing.md` is more like a standard

**Comment by tomaskikutis** [comment]
I thought I was putting it in the root :) Well, I moved it to `CONTRIBUTING.md`

**Comment by pablopunk** [comment]
I guess this could be merge already, if someone has more suggestions they'll just submit another PR for discussion

**Pull request merged**
