### PR TITLE
Custom script tags on index.html

### PR DESCRIPTION
**Pull request by pablopunk**
SDESK-3781

We have a custom script on `index.html` only if `qumu` feature is enabled. As this is specific to fidelity, I created `features.scriptTags` field to inject custom scripts on superdesk.

In repos like `superdesk-fi` we can put:

```js
features: {
   ...,
   scriptTags: [ 'https://video.fidelity.tv/widgets/1/application.js' ]
}
```

Thoughts on this? @hlmnrmr @petrjasek  @tomaskikutis

### CODE REVIEW

**Comment by petrjasek** [comment]
makes sense, but wouldn't add it into features, more like have it on its own, features are more like feature flags to set something on/off

**Comment by pablopunk** [comment]
@petrjasek that makes sense, I'll update the PR. BTW why do we also have an index.html (no .js) ?

**Comment by petrjasek** [comment]
that's the one which is generated, it's not on github

**Comment by tomaskikutis** [comment]
Sorry for the late notice, but I just realized that the scope of the task is a bit off. This script isn't a dependence of Fidelity, but of a qumu video plugin which is a thing Fidelity uses.

**Comment by pablopunk** [comment]
@tomaskikutis then it should still need to be on fidelity's repo right?

**Comment by tomaskikutis** [comment]
It doesn't help much extracting only loading of the lib, but not all components related to qumu which are still in the core. I'd close this for now and come back to it later when we have superdesk extension API and can extract the entire qumu properly together with this script.

**Comment by tomaskikutis** [comment]
Sorry for two comments, I wanted to add a space and clicked ctrl+enter which submitted a comment. I think it would go to some kind of superdesk-plugins repo, and it would be initialized and configured from fidelity's repo

**Comment by pablopunk** [comment]
I'll close this PR and the ticket for now then

**Pull request closed without merging**
