### PR TITLE
feat(config): use client_config resource to get allowed auth methods

### PR DESCRIPTION
**Pull request by petrjasek**
SDESK-1327

uses https://github.com/superdesk/superdesk-core/pull/942

### CODE REVIEW

**Comment by petrjasek** [comment]
I might put it here, but I'm struggling with naming - would like to add a service for this, but we already use config..

**Comment by petrjasek** [comment]
@naspeh added it here

**Comment by petrjasek** [comment]
ups, we have even `serverConfig` service already. will call it `serverClientConfig` or something :wink:

**Comment by naspeh** [comment]
Maybe we can combine two of them to one? We can set that it requires authorization for modifying the `superdesk.server_config`, but all setting can be fetched without auth... What do you think?

**Comment by petrjasek** [comment]
renamed it to `deployConfig` for now

**Pull request merged**
