### PR TITLE
Do not limit header height

### PR DESCRIPTION
**Pull request by tomaskikutis**
SDESK-6364

### CODE REVIEW

**Review by petrjasek — APPROVED** [review]

**Review by fritzSF — COMMENTED** [review]
Whitout limiting the header hight there will be no transition. I'm against killing general UX features because of requests of one customer or some edge cases. IMO this is generally not the right way to go.

**Review by fritzSF — CHANGES_REQUESTED** [review]
Limiting the height to a large value (e.g. 100vh, 2000px or similar) might be sufficient to solve the problem and still preserve some transitioning while opening the header.

**Comment by tomaskikutis** [comment]
https://user-images.githubusercontent.com/2076953/156609316-fb94322c-dabd-4cef-bb12-8a5ca5faaab2.mp4

**Review by fritzSF — APPROVED** [review]

**Comment by fritzSF** [comment]
Niice! Looks much better than before.

**Review by pavlovicnemanja — APPROVED** [review]

**Pull request merged**
