### PR TITLE
fix: react-awesome-slider Name expected / uglifyJs

### PR DESCRIPTION
**Pull request by tomaszrondio**
needed for publisher

### CODE REVIEW

**Comment by tomaskikutis** [comment]
Can you explain the change? Why is it needed? What does it have to do with `react-awesome-slider`?

**Comment by tomaszrondio** [comment]
i am trying to fix this one https://travis-ci.org/superdesk/superdesk/builds/616567601#L2673

**Comment by tomaskikutis** [comment]
What's the issue there? The current uglifier crashes when handling `react-awesome-slider` code? Does it build well if uglifying is disabled?

**Comment by tomaszrondio** [comment]
it looks like it. There is no real explanation nor fix for that. Only suggestions from github or stackoverflow. Locally it works perfectly fine. I am blind fixing...

**Comment by pavlovicnemanja** [comment]
@tomaszrondio we don't use `superdesk:master` branch for PR's, please make PR to `superdesk:develop` branch

**Comment by tomaskikutis** [comment]
I've switched the base. You can do that even after the PR was submitted.

**Comment by tomaszrondio** [comment]
close this one. I will add my changes to develop, test locally and do new PR from develop to develop.

**Pull request closed without merging**
