### PR TITLE
add email field to desk config

### PR DESCRIPTION
**Pull request by petrjasek**
CPCN-502

### CODE REVIEW

**Comment by tomaskikutis** [comment]
is it really for `CPCN-502`? I don't see anything about emails there

**Comment by petrjasek** [comment]
you're right, it's rather CPCN-503

**Review by tomaskikutis — APPROVED** [review]

**Comment by tomaskikutis** [comment]
I'm thinking maybe we should do it conditional, because it doesn't have any use in superdesk

**Comment by tomaskikutis** [comment]
Ideal scenario would be being able to set it up from extensions API

**Comment by petrjasek** [comment]
there is a specific ticket for the hiding later

**Pull request merged**
