### PR TITLE
fix(ui-fixes): Fixed issue with splitter and swimline view

### PR DESCRIPTION
**Pull request by pavlovicnemanja**
SDESK-5844 and SDESK-5841

### CODE REVIEW

**Comment by petrjasek** [comment]
hi @pavlovicnemanja is there a ticket?

**Comment by pavlovicnemanja** [comment]
> hi @pavlovicnemanja is there a ticket?

SDESK-5844 and SDESK-5841

**Comment by petrjasek** [comment]
can we seperate those 2 fixes? I need 5841 in 2.2 and 5844 in 2.3. or will this 5844 work with 2.2 no problem?

**Comment by pavlovicnemanja** [comment]
> can we seperate those 2 fixes? I need 5841 in 2.2 and 5844 in 2.3. or will this 5844 work with 2.2 no problem?

It's old issue, we can without problem push it to 2.2

**Review by tomaskikutis — APPROVED** [review]

**Pull request merged**
