### PR TITLE
fixed: Content type filter is empty in publish queue on sdp-master

### PR DESCRIPTION
**Pull request by GyanP**
https://dev.sourcefabric.org/browse/SDESK-3655

### CODE REVIEW

**Comment by tomaskikutis** [comment]
Are duplicates really the problem? Shouldn't `vocabularies.getVocabulary('type')` already return unique items?

**Comment by GyanP** [comment]
> Are duplicates really the problem? Shouldn't `vocabularies.getVocabulary('type')` already return unique items?

Yeah, `vocabularies.getVocabulary('type')` returns duplicate data. Also, you can check it on sdp-master, when you go to `publish queue`, you'll get that error in the browser console.

**Comment by tomaskikutis** [comment]
I've just checked the [database of sdp-master](https://user-images.githubusercontent.com/2076953/49140356-c6746f80-f2fc-11e8-8839-8a52596e65aa.png). The vocabulary is full of duplicates. I think the database needs to be fixed and nothing needs to be done on the client.

What do you think @petrjasek @jerome-poisson @ioanpocol ?

**Comment by petrjasek** [comment]
yep that db is definitely in wrong state, wondering how it could happened given that it's unmanageable

**Comment by tomaskikutis** [comment]
I've created SDESK-3683 to fix the database.

Gyan, can you close this PR and take the ticket out of the sprint? We'll resolve it once the database is fixed.

**Comment by GyanP** [comment]
> I've created SDESK-3683 to fix the database.
> 
> Gyan, can you close this PR and take the ticket out of the sprint? We'll resolve it once the database is fixed.

Ok, I will close the PR. And about the ticket, should I set the status to open? Which sprint should I move this ticket to?

**Comment by tomaskikutis** [comment]
Yep, set the status to open. Just remove it from the current sprint so it's not in any sprint.

**Comment by tomaskikutis** [comment]
Sorry, clicked "close" instead of "comment". Well, we were about to close it anyway :smile:

**Pull request closed without merging**
