### PR TITLE
win new lines converted to unix, trailing spaces removed

### PR DESCRIPTION
**Pull request by vied12**
```bash
# windows new line to Unix new line
find ./ -type f -exec dos2unix {} \;
# Remove trailing spaces
find ./ -type f -exec sed -i 's/[ \t]*$//' {} \;
```

### CODE REVIEW

**Comment by Aca-jov** [comment]
:+1:

**Comment by eozan** [comment]
:+1:

**Comment by ioanpocol** [comment]
:+1:

**Comment by vied12** [comment]
@ioanpocol not only, you need to exclude images, svg, fonts, po files...

**Pull request merged**
