### PR TITLE
add cache param to dataApi.findOne

### PR DESCRIPTION
**Pull request by petrjasek**
need to force refresh a computed resource in planning

### CODE REVIEW

**Review by tomaskikutis — APPROVED** [review]
I think we should drop that cache thing in the future completelly. Cache that caches only for the duration of 1 request is pretty useless. We should probably rather fix the usages and reduce the number of calls. Do you remember why did you add that cache option to begin with?

**Comment by petrjasek** [comment]
yep I think it was there for angular where multiple requests could fire at the same time due to digest handling and then this would avoid certain duplicated queries, like when fetching the same vocabulary

**Comment by tomaskikutis** [comment]
Do you remember if it was authoring or another part of the app?

**Comment by petrjasek** [comment]
I don't remember where exactly

**Pull request merged**
