### PR TITLE
fixed panel footer UI

### PR DESCRIPTION
**Pull request by dzonidoo**
SDESK-6942

### CODE REVIEW

**Review by tomaskikutis — APPROVED** [review]
I suspect the issue might have been markup of `PanelFooter` changing on ui-framework side

**Review by tomaskikutis — APPROVED** [review]
I suspect the issue might have been markup of `PanelFooter` changing on ui-framework side

**Comment by dzonidoo** [comment]
I do not think like that... only the absence of the ButtonGroup component or style of buttons is a problem in this case. I chose to wrap button

**Comment by tomaskikutis** [comment]
I checked an older commit and the issue was still there, so you might be correct. One more thing - check usages for when `markupV2` is `true` and see if your change still looks good in that case.

**Comment by dzonidoo** [comment]
I checked and it works

**Comment by tomaskikutis** [comment]
ok thanks

**Pull request merged**
