### PR TITLE
feat(takes): add config option to hide takes related func

### PR DESCRIPTION
**Pull request by petrjasek**
SD-5090

### CODE REVIEW

**Comment by mdhaman** [comment]
@petrjasek the same check is required for `send and continue` in send-to panel and `associate as take` in the related-item widget.

**Comment by petrjasek** [comment]
thx, I was sure I'm missing something :wink:

**Comment by gbbr** [comment]
LGTM

**Comment by mdhaman** [comment]
:+1:

**Comment by akintolga** [comment]
:+1:

**Pull request merged**
