### PR TITLE
feature(planning): add google api key config

### PR DESCRIPTION
**Pull request by thnkloud9**
will be used by planning component

### CODE REVIEW

**Comment by gbbr** [comment]
Which Google API is this for? I think they have more than one :-)

**Comment by thnkloud9** [comment]
@gbbr , as far as I am aware google apis are now controlled via developer console and enabled / disabled per app there.  In this particular case, at this time, I am only using maps and places apis, but there is no reason that I could not enable other google apis later for the same key.  At least that has been my understanding of the current google apis paradigm.  However, please correct me if I'm wrong, as I would def. not claim to be an expert here.

**Comment by gbbr** [comment]
Neither am I am expert. I was just wondering whether we could be more specific about what API this is, but since you say that the key is valid for all of their APIs, then this looks good to me.

**Comment by thnkloud9** [comment]
yep, makes sense to add.  should be there now.  thanks!

**Pull request merged**
